# Generated by Django 5.0.14 on 2026-09-18 19:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='OIDCClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(help_text='Публичный идентификатор приложения', max_length=64, unique=True)),
                ('client_secret', models.CharField(help_text='Секретный ключ для проверки подлинности клиента', max_length=128)),
                ('name', models.CharField(help_text="Название приложения (например, 'Ecommerce Frontend')", max_length=100)),
                ('redirect_uri', models.URLField(help_text='URL,  куда перенаправлять пользователя после аутентификации')),
                ('is_active', models.BooleanField(default=True, help_text='Активен ли клиент (False = доступ отозван)')),
                ('owner', models.ForeignKey(help_text='Пользователь, который зарегистрировал это приложение', on_delete=django.db.models.deletion.CASCADE, related_name='oidc_clients', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
